import Head from 'next/head'
import { Bookings } from '@billboards-org/ui/src/components/templates/Bookings'
import { IsLoggedIn } from '@billboards-org/ui/src/components/templates/IsLoggedIn'
import { IsOwner } from '@billboards-org/ui/src/components/templates/IsOwner'
import { Container } from '@billboards-org/ui/src/components/atoms/Container'

export default function Register() {
  return (
    <>
      <Head>
        <title>Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <IsLoggedIn>
            {(uid) => (
              <IsOwner uid={uid}>
                <Bookings />
              </IsOwner>
            )}
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
