import Head from 'next/head'
import { AuthLayout } from '@billboards-org/ui/src/components/molecules/AuthLayout'
import { RegisterForm } from '@billboards-org/ui/src/components/templates/RegisterForm'

export default function Register() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AuthLayout title="Register">
          <RegisterForm />
        </AuthLayout>
      </main>
    </>
  )
}
