import { IsLoggedIn } from '@billboards-org/ui/src/components/templates/IsLoggedIn'
import { IsAgent } from '@billboards-org/ui/src/components/templates/IsAgent'
import Head from 'next/head'
import { ShowBillboardsAgent } from '@billboards-org/ui/src/components/templates/AgentPage/AgentPage'
import { FormProviderFilterBillboards } from '@billboards-org/forms/src/filterBillboards'
import { FilterOwnerBillboards } from '@billboards-org/ui/src/components/organisms/FilterOwnerBillboards'
import { Container } from '@billboards-org/ui/src/components/atoms/Container'

export default function Login() {
  return (
    <>
      <Head>
        <title>Billboards | Agent | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {' '}
        <Container>
          <IsLoggedIn>
            {(uid) => (
              <IsAgent uid={uid}>
                <FormProviderFilterBillboards>
                  <div className="flex justify-end my-2">
                    <FilterOwnerBillboards />
                  </div>
                  <ShowBillboardsAgent />
                </FormProviderFilterBillboards>
              </IsAgent>
            )}
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
