import { IsLoggedIn } from '@billboards-org/ui/src/components/templates/IsLoggedIn'
import { Expenses } from '@billboards-org/ui/src/components/templates/Expenses'
import Head from 'next/head'
import { Container } from '@billboards-org/ui/src/components/atoms/Container'

export default function Login() {
  return (
    <>
      <Head>
        <title>Expenses | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <IsLoggedIn>
            <Expenses />
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
