import Head from 'next/head'
import { AdvertiserWishlist } from '@billboards-org/ui/src/components/templates/AdvertiserWishlist'
import { IsLoggedIn } from '@billboards-org/ui/src/components/templates/IsLoggedIn'
import { Container } from '@billboards-org/ui/src/components/atoms/Container'

export default function FavoritesPage() {
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <IsLoggedIn>{(uid) => <AdvertiserWishlist uid={uid} />}</IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
