import Head from 'next/head'
import { Hero } from '@billboards-org/ui/src/components/organisms/Hero'
import { HeroOwner } from '@billboards-org/ui/src/components/organisms/HeroOwner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <HeroOwner />
      </main>
    </>
  )
}
