import Head from 'next/head'
import {
  BillboardCity,
  MovingAroundCityCamera,
} from '../components/BillboardCity'
import { useRouter } from 'next/navigation'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Billboards | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BillboardCity>
          <div className="container mx-auto text-left">
            <h1 className="font-black text-8xl">Stand out.</h1>
            <p className="max-w-xs">
              Elevate your brand with strategic billboard advertising in prime
              locations!
            </p>
            <button
              onClick={() => router.push('/billboards')}
              className="px-3 py-1 mt-4 text-black bg-white rounded-0"
            >
              Find ad spaces
            </button>
          </div>
        </BillboardCity>
        <div className="h-24 bg-black" />
        <BillboardCity camera={<MovingAroundCityCamera />} height="h-[76vh]">
          <div className="container z-10 mx-auto text-left">
            <h1 className="font-black text-8xl">Install our billboards!</h1>
            <p className="max-w-xs">
              Discover how our billboards can turn your property into a
              consistent income source. Join us today!
            </p>
            <button
              className="px-3 py-1 mt-4 text-black bg-white rounded-0"
              onClick={() =>
                router.push(process.env.NEXT_PUBLIC_OWNER_URL || '')
              }
            >
              List your space
            </button>
          </div>
        </BillboardCity>{' '}
        <div className="h-24 bg-black" />
      </main>
    </>
  )
}
